type ModelTypes =
  | 'core'
  | 'group'
  | 'background'
  | 'text'
  | 'textstatic'
  | 'textdynamic'
  | 'textoptions'
  | 'image'
  | 'imagestatic'
  | 'imagedynamic'
  | 'imageoptions'
  | 'imageoptionsmultiple'
  | 'imagestaticquery'
  | 'imageoptionsquery'
  | 'imageoptionsmultiplequery'
  | 'textstaticquery'
  | 'textoptionsquery'

export default ModelTypes
